pipelines:
  default:
    - step:
        name: Sync GitHub Mirror
        image: alpine/git:latest
        clone:
          enabled: false
        script:
          - git clone --bare git@bitbucket.org:marco-rasori-iit/ace-java.git
          - cd ace-java.git
          - git push --mirror git@github.com:sifis-home/ace-ucs.git