name: Maven Tests
on:
  push:
    branches:
      - sifis-home

jobs:
  Tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [
          '8.0.x',
          '11.0.x',
          '12.0.x',
          '13.0.x',
          '14.0.x',
          '15.0.x',
        ]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          architecture: x64
          distribution: 'zulu'
          cache: 'maven'

      - name: Install MySql for tests
        run: |
          echo "mysql-server mysql-server/root_password password root" | sudo debconf-set-selections
          echo "mysql-server mysql-server/root_password_again password root" | sudo debconf-set-selections
          sudo apt-get -y install mysql-server
          sudo systemctl start mysql.service
          echo "root" > db.pwd # Root username
          echo "root" >> db.pwd # Root pw

      - name: Run the tests
        run: mvn clean --batch-mode test